[versions]
jetbrainsAnnotations = "26.0.2"
projectReactor = "3.7.7"
guava = "33.3.1-jre"

slf4j = "2.0.13"
springBoot = "3.5.8"

lang3 = "3.18.0"
micrometer = "1.16.0"
mockito = "5.10.0"
junitJupiter = "5.12.2"
mockserver = "5.15.0"
tableFormat = "1.2.4"



[libraries]

jetbrainsAnnotations = { group = "org.jetbrains", name = "annotations", version.ref = "jetbrainsAnnotations" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }

lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "lang3" }

projectReactorTest = { group = "io.projectreactor", name = "reactor-test", version.ref = "projectReactor" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }


# Spring Boot core and starters
springBootStarterWebflux = { group = "org.springframework.boot", name = "spring-boot-starter-webflux", version.ref = "springBoot" }
springBootStarterTest = { group = "org.springframework.boot", name = "spring-boot-starter-test", version.ref = "springBoot" }

# Micrometer
micrometerRegistryPrometheus = { group = "io.micrometer", name = "micrometer-registry-prometheus", version.ref = "micrometer" }

# Testing
junitJupiterApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junitJupiter" }
junitJupiterEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junitJupiter" }
mockitoCore = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockitoJunitJupiter = { group = "org.mockito", name = "mockito-junit-jupiter", version.ref = "mockito" }
junitPlatformLauncher = { group = "org.junit.platform", name = "junit-platform-launcher" }

# MockServer
mockserverNetty = { group = "org.mock-server", name = "mockserver-netty", version.ref = "mockserver" }
mockserverClient = { group = "org.mock-server", name = "mockserver-client-java", version.ref = "mockserver" }



[plugins]

